Update approvals.yml

diff --git a/.github/workflows/approvals.yml b/.github/workflows/approvals.yml
--- a/.github/workflows/approvals.yml
+++ b/.github/workflows/approvals.yml
@@ -36,8 +36,13 @@ jobs:
                   fi
               fi
           done
-
+          
           required_approvals=2
+          if [ "$approval_usrs" = '' ]; then
+            echo "Error: at least ${required_approvals} approvals needed to be able to merge this PR (currently: 0)."
+            exit 1
+          fi
+          
           current_approvals=$(echo "${approval_usrs}" | wc -l)
           if [  "$current_approvals" -lt "$required_approvals" ]; then
               echo "Error: at least ${required_approvals} approvals needed to be able to merge this PR (currently: $current_approvals)."
