add changes for today

diff --git a/.github/workflows/unique_approvals.yaml b/.github/workflows/unique_approvals.yaml
--- a/.github/workflows/unique_approvals.yaml
+++ b/.github/workflows/unique_approvals.yaml
@@ -1,32 +1,48 @@
 name: unique-pr-approvals
 on: 
-  pull_request:
+  pull_request_review:
+    types:
+      - submitted
 
 jobs:
   check-pr:
     runs-on: ubuntu-latest
     steps:
+      - name: Get PR Number 
+        id: get-pr-number
+        run: |
+          pr_number=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
+          echo "::set-output name=val::${pr_number}"
+
       - name: Get Previous Review
         id: get-prev-review
         run: |
-          pr_number=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
+          pr_number=${{ steps.get-pr-number.outputs.val }}
           reviews=$(curl -s -X GET \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/reviews")
 
-          reviewed='true' 
-          # TODO! check if the reviews are empty
+          # !!! CHANGE THIS IF THE NUMBER OF NEEDED REVIEWS CHANGE !!!
+          # this part is subject to change (could be removed)
+          max_reviews=2
+          reviews_count=$(echo "$reviews" | jq length)
+          if [ ${reviews_count} -ge ${max_reviews} ]; then
+            echo "Error: the PR has at least ${max_reviews} reviews already."
+            exit 1 # this should terminate the job
+          fi
 
-          if [ ${reviewed} == 'true' ]; then
+          if [ $reviews_count -gt 0 ]; then
+            # the jq part should be considered 
             last_review=$(echo "${reviews}" | jq -r 'map(select(.state == "APPROVED")) | last')
             last_reviewer_grp=$(echo "${last_reviewer_grp}" | jq -r '.author_association')
-
-            echo "::set-output name=grp::${last_reviewer_grp}"
 
           else
             echo "::set-output name=grp::''"
           fi
+
+          echo "::set-output name=grp::${last_reviewer_grp}"
+
 
       - name: Check if the current review is valid
         id: valid-curr-review 
@@ -39,7 +55,7 @@ jobs:
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/users/${{ github.actor }}/repos" | jq -r '.[].owner.type')
 
-            # two users with the same group have reviewed the PR
+            # checking if the current and previous groups are unique
             if [ ${current_grp} != ${prev_grp} ]; then
               echo "::set-output name=res::'VALID'"
 
@@ -47,6 +63,7 @@ jobs:
               echo "::set-output name=res::'INVALID'"
             fi
             
+          # no previous reviews
           else
             echo "::set-output name=res::'VALID'"
           fi
@@ -55,12 +72,16 @@ jobs:
       - name: Accept PR
         if: ${{ steps.valid-curr-review.outputs.res == 'VALID' }}
         run: |
-          # TODO! proper action - current one is merge, review might be needed
-          :'
-          pr_number=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
-          curl -s -X PUT \
+          review_content="${{ github.event.review.content }}"
+
+          # try this if the one above doesn't work
+          # review_content=$(echo "${{ github.event.review.content }}" | jq '.')
+        
+          pr_number=${{ steps.get-pr-number.outputs.val }}
+
+          # this pushes the pr review
+          curl -s -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${pr_number}/merge"
-          '
-
+            -d "${review_content}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews"
